### ISSUE TITLE
Scoreboard executable not displaying correctly

### ISSUE THREAD

**Issue by dookgit** [iDigitalFlame/Scorebot-Scoreboard#1]
Hey dude.

So i've had no luck compiling the scoreboard executable using the scripts (i'm a complete noob with Go)
So i've been using the pre-compiled release files you've got.

1.6 works fine, see's my scorebot and displays sweet.
But 1.7 upwards doesn't, it displays the page but in text, as opposed to rendered HTML.  I'll attach a screenshot.

![image](https://user-images.githubusercontent.com/10006917/76510456-5eb84880-649d-11ea-8c58-2a0042f1a8fc.png)

I'm running Ubuntu 18.04.3 if that matters. And i have the html folder in the same folder as the executable.

Not a real issue at the moment as i have a working scoreboard, just an FYI.
Lemme know if you need anymore info.

**Comment by iDigitalFlame** [comment]
Fixed that issue in release v2. For some reason the webserver "Context-Type" flag was not getting set.
