### ISSUE TITLE
Request = Ability to hide a game/only show 1 gave on the Scoreboard

### ISSUE THREAD

**Issue by dookgit** [iDigitalFlame/Scorebot-Scoreboard#2]
So.

I have 2 games on the scorebot itself.  1 for the live game, the other as "staging" which holds hosts that have been setup in the scorebot system. So when i want to add these to the live game i can just easily re-assign them, and they move from 1 scoreboard to the other (Just quicker than manually adding hosts/services)

e.g 
http://<IP>:8080/game/1 = Staging Game
http://<IP>:8080/game/2 = Live Game

I'd like to be able to hide the "Staging Game" from players, so they can't get a sneak peak at new servers i'm gonna add.
This might be hard within Scorebot, but even if you can specify the game number in scoreboard.config, so that it will then only show that 1 scoreboard

e.g 
http://<IP>:8080 (When scoreboard.config has game = 3) will only display http://<IP>:8080/game/3 (and nothing else)

Make sense?

Cheers

**Comment by iDigitalFlame** [comment]
Currently games that are considered "Canceled" or "Completed" won't show up in the games list. You can set this in the Admin settings for the game.

Code logic:
[Removing non-active Games from queue list](https://github.com/iDigitalFlame/Scorebot-Scoreboard/blob/59920f2d39636135d348add966477ebda1d6aad2/scoreboard/game/manager.go#L192)
[How active status is caculated](https://github.com/iDigitalFlame/Scorebot-Scoreboard/blob/59920f2d39636135d348add966477ebda1d6aad2/scoreboard/game/game.go#L79)

Agreed, this is not a clean solution and will rely on an update to Scorebot-Core to add proper support.
Will add this to my planned feature list.

Thanks!

**Comment by iDigitalFlame** [comment]
Reading mistake, the game should also be removed from the Games list, reopening to track fix.

**Comment by iDigitalFlame** [comment]
Just added 2 commits to main that will NOT display games that are set to "Canceled".
The current code doesn't have a pre-built release yet and will be added into the roll-up release later this month. (It can be built using "build.sh" to get the new update immediately).

Thanks!
